# Generated by Django 2.2.3 on 2019-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20190906_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pass_percentage',
        ),
        migrations.AddField(
            model_name='test',
            name='pass_percentage',
            field=models.CharField(choices=[('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80')], default='30', max_length=2, verbose_name='Pass Percentage'),
        ),
    ]
